version: "3.8"

# For local development, only database is running
#
# docker-compose up -d
# uvicorn app.main:app --reload
#
services:
  db-local:
    restart: always
    image: postgres:15.3
    volumes:
      - ${POSTGRES_HOME_DIR}/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DEFAULT_DATABASE_DB}
      - POSTGRES_USER=${DEFAULT_DATABASE_USER}
      - POSTGRES_PASSWORD=${DEFAULT_DATABASE_PASSWORD}
    env_file:
      - .env
    ports:
      - "${DEFAULT_DATABASE_PORT}:5432"
    networks:
      - backend

  # 서비스명
  # Redis Cluster 설정
  redis-cluster-creator-local:
    # 사용할 이미지
    image: redis:latest
    # 컨테이너명 설정
    container_name: redis-cluster-creator-local
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    depends_on:
      - redis-cluster-local
      - redis-node2-local
      - redis-node3-local
    # 명령어 설정
    command: redis-cli --cluster create 127.0.0.1:6379 127.0.0.1:6380 127.0.0.1:6381 --cluster-yes
    network_mode: "service:redis-cluster-local"
    # 네트워크 설정

  # Redis Node1 설정
  redis-cluster-local:
    image: redis:latest
    container_name: redis-cluster-local
    restart: always
    volumes:
      - ./redis-node.conf:/usr/local/etc/redis.conf
    command: ["redis-server", "/usr/local/etc/redis.conf", "--port", "6379"]
    ports:
      - 6379:6379
      - 6380:6380
      - 6381:6381

  # Redis Node1 설정
  redis-node2-local:
    image: redis:latest
    container_name: redis-node2-local
    restart: always
    volumes:
      - ./redis-node.conf:/usr/local/etc/redis.conf
    command: ["redis-server", "/usr/local/etc/redis.conf", "--port", "6380"]
    network_mode: "service:redis-cluster-local"
  # Redis Node1 설정
  redis-node3-local:
    image: redis:latest
    container_name: redis-node3-local
    restart: always
    volumes:
      - ./redis-node.conf:/usr/local/etc/redis.conf
    command: ["redis-server", "/usr/local/etc/redis.conf", "--port", "6381"]
    network_mode: "service:redis-cluster-local"

networks:
  backend:
    driver: "bridge"
