"""Add gym info relationship in workout promise

Revision ID: 1b756c8a6733
Revises: 1d2b43b84193
Create Date: 2023-02-17 20:53:13.266369

"""
from alembic import op
import sqlalchemy as sa
import app.models.guid


# revision identifiers, used by Alembic.
revision = "1b756c8a6733"
down_revision = "1d2b43b84193"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workout_promise",
        sa.Column("gym_info_id", app.models.guid.GUID(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_workout_promise_gym_info_id_gym_info"),
        "workout_promise",
        "gym_info",
        ["gym_info_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_workout_promise_gym_info_id_gym_info"),
        "workout_promise",
        type_="foreignkey",
    )
    op.drop_column("workout_promise", "gym_info_id")
    # ### end Alembic commands ###
