"""Modify ChatRoom title and description Nullable

Revision ID: c234559242d4
Revises: e4f2b0ec1ec9
Create Date: 2023-03-02 15:19:58.067612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c234559242d4'
down_revision = 'e4f2b0ec1ec9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_room', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('chat_room', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_room', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('chat_room', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
