"""add_notification_model

Revision ID: fb8ee6ef1f8a
Revises: 1cbb1843cae1
Create Date: 2023-03-21 22:28:06.512360

"""
from alembic import op
import sqlalchemy as sa
import app.models.guid


# revision identifiers, used by Alembic.
revision = "fb8ee6ef1f8a"
down_revision = "12d91a8a9f88"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("id", app.models.guid.GUID(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("notification_type", sa.String(), nullable=False),
        sa.Column("recipient_id", app.models.guid.GUID(), nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["user.id"],
            name=op.f("fk_notification_recipient_id_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification")
    # ### end Alembic commands ###
