"""Rename is_like to is_liked

Revision ID: 5146f0bd25ed
Revises: 0c967bd52657
Create Date: 2023-08-09 14:58:51.778915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5146f0bd25ed'
down_revision = '0c967bd52657'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_like', sa.Column('is_liked', sa.Integer(), nullable=False))
    op.drop_column('comment_like', 'is_like')
    op.add_column('post_like', sa.Column('is_liked', sa.Boolean(), nullable=False))
    op.drop_column('post_like', 'is_like')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_like', sa.Column('is_like', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('post_like', 'is_liked')
    op.add_column('comment_like', sa.Column('is_like', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('comment_like', 'is_liked')
    # ### end Alembic commands ###
