"""Add last read at column in ChatRoomMember table 

Revision ID: 46e94818f02c
Revises: 59077bdd9407
Create Date: 2023-01-28 16:41:28.969645

"""
from alembic import op
import sqlalchemy as sa
from app.models import guid

# revision identifiers, used by Alembic.
revision = "46e94818f02c"
down_revision = "59077bdd9407"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_room_member",
        sa.Column("last_read_message_id", guid.GUID(), nullable=True),
    )
    op.add_column(
        "chat_room_member", sa.Column("last_read_at", sa.TIMESTAMP(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_room_member", "last_read_at")
    op.drop_column("chat_room_member", "last_read_message_id")
    # ### end Alembic commands ###
