"""Add idx and group chat boolean in Chat Room Model

Revision ID: a849155b67a2
Revises: 754cb5088631
Create Date: 2023-03-07 17:06:00.010248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a849155b67a2'
down_revision = '754cb5088631'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_room', sa.Column('is_group_chat', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_index(op.f('ix_chat_room_is_group_chat'), 'chat_room', ['is_group_chat'], unique=False)
    op.create_index(op.f('ix_chat_room_is_private'), 'chat_room', ['is_private'], unique=False)
    op.create_index(op.f('ix_chat_room_name'), 'chat_room', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_room_name'), table_name='chat_room')
    op.drop_index(op.f('ix_chat_room_is_private'), table_name='chat_room')
    op.drop_index(op.f('ix_chat_room_is_group_chat'), table_name='chat_room')
    op.drop_column('chat_room', 'is_group_chat')
    # ### end Alembic commands ###
