"""fix sender type as workout participant

Revision ID: 35fc620e3894
Revises: 1142e7557ade
Create Date: 2023-03-30 15:13:39.717162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35fc620e3894'
down_revision = '1142e7557ade'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_notification_workout_sender_id_user', 'notification_workout', type_='foreignkey')
    op.create_foreign_key(op.f('fk_notification_workout_sender_id_workout_participant'), 'notification_workout', 'workout_participant', ['sender_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_notification_workout_sender_id_workout_participant'), 'notification_workout', type_='foreignkey')
    op.create_foreign_key('fk_notification_workout_sender_id_user', 'notification_workout', 'user', ['sender_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
