"""Fix is liked field type

Revision ID: 3711c3442d81
Revises: f91ad2bca21f
Create Date: 2023-08-10 00:49:48.238172

"""
from email.policy import default
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3711c3442d81"
down_revision = "f91ad2bca21f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comment_like",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
    )
    op.add_column(
        "comment_like",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
    )
    op.add_column(
        "post_like",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
    )
    op.add_column(
        "post_like",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
    )
    op.alter_column(
        "post_like",
        "is_liked",
        existing_type=sa.BOOLEAN(),
        type_=sa.Integer(),
        existing_nullable=False,
        default=1,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "post_like",
        "is_liked",
        existing_type=sa.Integer(),
        type_=sa.BOOLEAN(),
        existing_nullable=False,
    )
    op.drop_column("post_like", "updated_at")
    op.drop_column("post_like", "created_at")
    op.drop_column("comment_like", "updated_at")
    op.drop_column("comment_like", "created_at")
    # ### end Alembic commands ###
