"""Add idx in user model

Revision ID: 5155c0cabc3e
Revises: 5fd651c7cc19
Create Date: 2023-04-12 17:01:34.684647

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "5155c0cabc3e"
down_revision = "5fd651c7cc19"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_user_phone_number"), "user", ["phone_number"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_phone_number"), table_name="user")
    # ### end Alembic commands ###
