"""Add AiCoacing Like model

Revision ID: f19eafff1b8e
Revises: 96ad8fc766d3
Create Date: 2023-09-18 17:52:48.528763

"""
from alembic import op
import sqlalchemy as sa
import app.models.guid

# revision identifiers, used by Alembic.
revision = "f19eafff1b8e"
down_revision = "96ad8fc766d3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_coaching_like",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("is_liked", sa.Integer(), nullable=False),
        sa.Column("user_id", app.models.guid.GUID(), nullable=False),
        sa.Column("ai_coaching_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ai_coaching_id"],
            ["ai_coaching.id"],
            name=op.f("fk_ai_coaching_like_ai_coaching_id_ai_coaching"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_ai_coaching_like_user_id_user"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_coaching_like")),
        sa.UniqueConstraint("user_id", "ai_coaching_id", name=op.f("uq_ai_coaching_like_user_id")),
    )
    op.create_index(op.f("ix_ai_coaching_like_ai_coaching_id"), "ai_coaching_like", ["ai_coaching_id"], unique=False)
    op.create_index(op.f("ix_ai_coaching_like_id"), "ai_coaching_like", ["id"], unique=False)
    op.create_index(op.f("ix_ai_coaching_like_user_id"), "ai_coaching_like", ["user_id"], unique=False)
    op.add_column("post", sa.Column("summary", sa.String(length=200), nullable=True, comment="Ai Summary"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post", "summary")
    op.drop_index(op.f("ix_ai_coaching_like_user_id"), table_name="ai_coaching_like")
    op.drop_index(op.f("ix_ai_coaching_like_id"), table_name="ai_coaching_like")
    op.drop_index(op.f("ix_ai_coaching_like_ai_coaching_id"), table_name="ai_coaching_like")
    op.drop_table("ai_coaching_like")
    # ### end Alembic commands ###
