"""Alter maxParticipants col to non-nullable

Revision ID: 5fb8af2a1d70
Revises: 1b756c8a6733
Create Date: 2023-02-18 18:43:05.138929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb8af2a1d70'
down_revision = '1b756c8a6733'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_promise', 'max_participants',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_promise', 'max_participants',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
