"""Fix workout models

Revision ID: 1d2b43b84193
Revises: 9db152de9913
Create Date: 2023-02-17 19:24:29.865713

"""
from alembic import op
import sqlalchemy as sa

import app.models.guid

# revision identifiers, used by Alembic.
revision = "1d2b43b84193"
down_revision = "9db152de9913"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workout_participant", sa.Column("is_admin", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "workout_participant",
        sa.Column("chat_room_member_id", app.models.guid.GUID(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_workout_participant_chat_room_member_id_chat_room_member"),
        "workout_participant",
        "chat_room_member",
        ["chat_room_member_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "workout_promise",
        sa.Column("chat_room_id", app.models.guid.GUID(), nullable=True),
    )
    op.alter_column(
        "workout_promise", "title", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "workout_promise", "description", existing_type=sa.VARCHAR(), nullable=False
    )
    op.create_foreign_key(
        op.f("fk_workout_promise_chat_room_id_chat_room"),
        "workout_promise",
        "chat_room",
        ["chat_room_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_workout_promise_chat_room_id_chat_room"),
        "workout_promise",
        type_="foreignkey",
    )
    op.alter_column(
        "workout_promise", "description", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "workout_promise", "title", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_column("workout_promise", "chat_room_id")
    op.drop_constraint(
        op.f("fk_workout_participant_chat_room_member_id_chat_room_member"),
        "workout_participant",
        type_="foreignkey",
    )
    op.drop_column("workout_participant", "chat_room_member_id")
    op.drop_column("workout_participant", "is_admin")
    # ### end Alembic commands ###
