"""Rename chat room member column

Revision ID: 18db465dffe3
Revises: 46e94818f02c
Create Date: 2023-01-29 17:40:02.517225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18db465dffe3'
down_revision = '46e94818f02c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_room_member', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.drop_column('chat_room_member', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_room_member', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('chat_room_member', 'is_admin')
    # ### end Alembic commands ###
