"""Add cost related fields in AiCoaching model

Revision ID: 96ad8fc766d3
Revises: 13278858b79b
Create Date: 2023-09-16 22:06:36.021986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "96ad8fc766d3"
down_revision = "13278858b79b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_coaching",
        sa.Column(
            "prompt_tokens", sa.Integer(), server_default="0", nullable=False, comment="number of tokens in prompt"
        ),
    )
    op.add_column(
        "ai_coaching",
        sa.Column(
            "completion_tokens",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="number of tokens in response",
        ),
    )
    op.add_column(
        "ai_coaching", sa.Column("cost", sa.Float(), server_default="0.0", nullable=False, comment="cost in USD")
    )
    op.add_column(
        "ai_coaching",
        sa.Column(
            "model_name",
            sa.String(length=100),
            server_default="gpt-3.5-turbo",
            nullable=False,
            comment="model used to generate response",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_coaching", "model_name")
    op.drop_column("ai_coaching", "cost")
    op.drop_column("ai_coaching", "completion_tokens")
    op.drop_column("ai_coaching", "prompt_tokens")
    # ### end Alembic commands ###
