"""Add address and gym column in User Model

Revision ID: c89fef1f823f
Revises: 924275248d5b
Create Date: 2023-02-14 15:57:21.569110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c89fef1f823f'
down_revision = '924275248d5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('gym', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'gym')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
