"""Set server default False is ai coach column

Revision ID: f91ad2bca21f
Revises: 5146f0bd25ed
Create Date: 2023-08-09 20:59:00.568509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f91ad2bca21f"
down_revision = "5146f0bd25ed"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "comment",
        "is_ai_coach",
        existing_type=sa.BOOLEAN(),
        server_default="0",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "comment",
        "is_ai_coach",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    # ### end Alembic commands ###
