"""add field to user model

Revision ID: ffebf314bc59
Revises: f4942167cc62
Create Date: 2023-07-04 16:27:41.185786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffebf314bc59'
down_revision = 'f4942167cc62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('workout_style', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('workout_routine', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('workout_partner_gender', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('district', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'district')
    op.drop_column('user', 'city')
    op.drop_column('user', 'workout_partner_gender')
    op.drop_column('user', 'workout_routine')
    op.drop_column('user', 'workout_style')
    # ### end Alembic commands ###
