"""Add last_active_at field in user model

Revision ID: 12d91a8a9f88
Revises: 1cbb1843cae1
Create Date: 2023-03-22 19:56:38.649768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "12d91a8a9f88"
down_revision = "1cbb1843cae1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_active_at")
    # ### end Alembic commands ###
