"""Fix fk constraint in AiCoaching model

Revision ID: 21278b7ccec3
Revises: f19eafff1b8e
Create Date: 2023-09-19 22:43:21.524267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21278b7ccec3'
down_revision = 'f19eafff1b8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_coaching', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ai_coaching', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_coaching', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('ai_coaching', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
