"""fix noti-model message nullable

Revision ID: 8ac29a2082ef
Revises: 2ce5d180a8d2
Create Date: 2023-04-02 23:21:21.374469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac29a2082ef'
down_revision = '2ce5d180a8d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
