"""fix sender_id and recipient_id can nullable

Revision ID: 1142e7557ade
Revises: 8b7e4d9f95c8
Create Date: 2023-03-25 15:41:20.545693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1142e7557ade"
down_revision = "8b7e4d9f95c8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "notification_workout",
        "sender_id",
        existing_type=postgresql.UUID(),
        nullable=True,
    )
    op.alter_column(
        "notification_workout",
        "recipient_id",
        existing_type=postgresql.UUID(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "notification_workout",
        "recipient_id",
        existing_type=postgresql.UUID(),
        nullable=False,
    )
    op.alter_column(
        "notification_workout",
        "sender_id",
        existing_type=postgresql.UUID(),
        nullable=False,
    )
    # ### end Alembic commands ###
