"""add workout part field to workout promise  model

Revision ID: 2bf2915736c5
Revises: ffebf314bc59
Create Date: 2023-08-08 13:33:16.422721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf2915736c5'
down_revision = 'ffebf314bc59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_promise', sa.Column('workout_part', sa.String(), nullable=True))
    op.create_index(op.f('ix_workout_promise_workout_part'), 'workout_promise', ['workout_part'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_promise_workout_part'), table_name='workout_promise')
    op.drop_column('workout_promise', 'workout_part')
    # ### end Alembic commands ###
