"""Add Relationships

Revision ID: 2c5cd9665654
Revises: 50609d968326
Create Date: 2023-01-12 16:07:44.895781

"""
from alembic import op
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2c5cd9665654"
down_revision = "50609d968326"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_room_member",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column(
            "chat_room_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column(
            "user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column("joined_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("left_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["chat_room_id"], ["chat_room.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_room_member_id"), "chat_room_member", ["id"], unique=False
    )
    op.drop_index("ix_chat_group_member_id", table_name="chat_group_member")
    op.drop_table("chat_group_member")
    op.add_column(
        "message",
        sa.Column(
            "user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True
        ),
    )
    op.add_column(
        "message",
        sa.Column(
            "chat_room_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True
        ),
    )
    op.create_foreign_key(
        None, "message", "user", ["user_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "message", "chat_room", ["chat_room_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "message", type_="foreignkey")
    op.drop_constraint(None, "message", type_="foreignkey")
    op.drop_column("message", "chat_room_id")
    op.drop_column("message", "user_id")
    op.create_table(
        "chat_group_member",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "joined_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "left_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("is_superuser", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="chat_group_member_pkey"),
    )
    op.create_index(
        "ix_chat_group_member_id", "chat_group_member", ["id"], unique=False
    )
    op.drop_index(op.f("ix_chat_room_member_id"), table_name="chat_room_member")
    op.drop_table("chat_room_member")
    # ### end Alembic commands ###
