"""Init

Revision ID: 59077bdd9407
Revises: 
Create Date: 2023-01-12 19:38:32.130294

"""
from alembic import op
import sqlalchemy as sa
import app

# revision identifiers, used by Alembic.
revision = "59077bdd9407"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audio",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("artist_name", sa.String(length=100), nullable=False),
        sa.Column("audio_url", sa.String(length=256), nullable=False),
        sa.Column("cover_image_url", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audio_id"), "audio", ["id"], unique=False)
    op.create_table(
        "chat_room",
        sa.Column("id", app.models.guid.GUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("created_by", app.models.guid.GUID(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_room_id"), "chat_room", ["id"], unique=False)
    op.create_table(
        "hashtag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_hashtag_id"), "hashtag", ["id"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", app.models.guid.GUID(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("phone_number", sa.String(length=100), nullable=False),
        sa.Column("profile_pic", sa.String(length=100), nullable=True),
        sa.Column("bio", sa.String(length=100), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Integer(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("last_active_at", sa.Integer(), nullable=True),
        sa.Column("workout_per_week", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audio_hashtag_association",
        sa.Column("audio_id", sa.Integer(), nullable=False),
        sa.Column("hashtag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["audio_id"],
            ["audio.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hashtag_id"],
            ["hashtag.id"],
        ),
        sa.PrimaryKeyConstraint("audio_id", "hashtag_id"),
    )
    op.create_table(
        "chat_room_member",
        sa.Column("id", app.models.guid.GUID(), nullable=False),
        sa.Column("chat_room_id", app.models.guid.GUID(), nullable=False),
        sa.Column("user_id", app.models.guid.GUID(), nullable=False),
        sa.Column("joined_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("left_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["chat_room_id"], ["chat_room.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_room_member_id"), "chat_room_member", ["id"], unique=False
    )
    op.create_table(
        "message",
        sa.Column("id", app.models.guid.GUID(), nullable=False),
        sa.Column("user_id", app.models.guid.GUID(), nullable=True),
        sa.Column("chat_room_id", app.models.guid.GUID(), nullable=True),
        sa.Column("text", sa.String(length=300), nullable=True),
        sa.Column("media_url", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_room_id"], ["chat_room.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_id"), "message", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_id"), table_name="message")
    op.drop_table("message")
    op.drop_index(op.f("ix_chat_room_member_id"), table_name="chat_room_member")
    op.drop_table("chat_room_member")
    op.drop_table("audio_hashtag_association")
    op.drop_table("user")
    op.drop_index(op.f("ix_hashtag_id"), table_name="hashtag")
    op.drop_table("hashtag")
    op.drop_index(op.f("ix_chat_room_id"), table_name="chat_room")
    op.drop_table("chat_room")
    op.drop_index(op.f("ix_audio_id"), table_name="audio")
    op.drop_table("audio")
    # ### end Alembic commands ###
