"""Add User and Chat Models

Revision ID: 5e6ed42e45d5
Revises: a9d2cd01a72c
Create Date: 2023-01-11 23:44:08.756231

"""
from alembic import op
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5e6ed42e45d5"
down_revision = "a9d2cd01a72c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_group_member",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("joined_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("left_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_group_member_id"), "chat_group_member", ["id"], unique=False
    )
    op.create_table(
        "chat_room",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column(
            "created_by", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_room_id"), "chat_room", ["id"], unique=False)
    op.create_table(
        "message",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("text", sa.String(length=300), nullable=True),
        sa.Column("media_url", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_id"), "message", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_id"), table_name="message")
    op.drop_table("message")
    op.drop_index(op.f("ix_chat_room_id"), table_name="chat_room")
    op.drop_table("chat_room")
    op.drop_index(op.f("ix_chat_group_member_id"), table_name="chat_group_member")
    op.drop_table("chat_group_member")
    # ### end Alembic commands ###
