"""Add user block relationship

Revision ID: 698f4fed8640
Revises: 5155c0cabc3e
Create Date: 2023-04-16 16:14:12.236680

"""
from alembic import op
import sqlalchemy as sa
import app.models.guid


# revision identifiers, used by Alembic.
revision = "698f4fed8640"
down_revision = "5155c0cabc3e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_block_list",
        sa.Column("user_id", app.models.guid.GUID(), nullable=False),
        sa.Column("blocked_user_id", app.models.guid.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["blocked_user_id"],
            ["user.id"],
            name=op.f("fk_user_block_list_blocked_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_user_block_list_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "blocked_user_id", name=op.f("pk_user_block_list")
        ),
    )
    op.create_index(
        op.f("ix_user_block_list_blocked_user_id"),
        "user_block_list",
        ["blocked_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_block_list_user_id"), "user_block_list", ["user_id"], unique=False
    )
    op.add_column(
        "user",
        sa.Column(
            "blocked", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "blocked")
    op.drop_index(op.f("ix_user_block_list_user_id"), table_name="user_block_list")
    op.drop_index(
        op.f("ix_user_block_list_blocked_user_id"), table_name="user_block_list"
    )
    op.drop_table("user_block_list")
    # ### end Alembic commands ###
