"""Add is private column in chatroom

Revision ID: 6d4e04a76cbf
Revises: 6616a3c2ca62
Create Date: 2023-02-03 13:08:06.483810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4e04a76cbf'
down_revision = '6616a3c2ca62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_room', sa.Column('is_private', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_room', 'is_private')
    # ### end Alembic commands ###
