"""Add workout promise status

Revision ID: 754cb5088631
Revises: c234559242d4
Create Date: 2023-03-02 16:37:13.863838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '754cb5088631'
down_revision = 'c234559242d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_promise', sa.Column('status', sa.String(), server_default='RECRUITING', nullable=False))
    op.create_index(op.f('ix_workout_promise_status'), 'workout_promise', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_promise_status'), table_name='workout_promise')
    op.drop_column('workout_promise', 'status')
    # ### end Alembic commands ###
