"""Add index at chat room member

Revision ID: 7daeea4f4b5c
Revises: a849155b67a2
Create Date: 2023-03-16 16:00:12.455954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7daeea4f4b5c'
down_revision = 'a849155b67a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_room_member_chat_room_id'), 'chat_room_member', ['chat_room_id'], unique=False)
    op.create_index(op.f('ix_chat_room_member_user_id'), 'chat_room_member', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_room_member_user_id'), table_name='chat_room_member')
    op.drop_index(op.f('ix_chat_room_member_chat_room_id'), table_name='chat_room_member')
    # ### end Alembic commands ###
