"""separate noti and noti-workout

Revision ID: 8b7e4d9f95c8
Revises: fb8ee6ef1f8a
Create Date: 2023-03-25 01:08:33.033658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.models.guid

# revision identifiers, used by Alembic.
revision = "8b7e4d9f95c8"
down_revision = "fb8ee6ef1f8a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_workout",
        sa.Column("id", app.models.guid.GUID(), nullable=False),
        sa.Column("notification_type", sa.String(), nullable=False),
        sa.Column("sender_id", app.models.guid.GUID(), nullable=False),
        sa.Column("recipient_id", app.models.guid.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["notification.id"],
            name=op.f("fk_notification_workout_id_notification"),
        ),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["workout_participant.id"],
            name=op.f("fk_notification_workout_recipient_id_workout_participant"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["user.id"],
            name=op.f("fk_notification_workout_sender_id_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_workout")),
    )
    op.drop_constraint(
        "fk_notification_recipient_id_user", "notification", type_="foreignkey"
    )
    op.drop_column("notification", "recipient_id")
    op.drop_column("notification", "notification_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification",
        sa.Column(
            "notification_type", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "notification",
        sa.Column(
            "recipient_id", postgresql.UUID(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "fk_notification_recipient_id_user",
        "notification",
        "user",
        ["recipient_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_table("notification_workout")
    # ### end Alembic commands ###
