"""Fix User Model

Revision ID: 924275248d5b
Revises: 4e500328aeef
Create Date: 2023-02-12 04:19:18.504149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "924275248d5b"
down_revision = "4e500328aeef"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("height", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column(
        "user",
        sa.Column(
            "gender", sa.String(length=50), server_default="other", nullable=False
        ),
    )
    op.add_column(
        "user", sa.Column("workout_level", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "user", sa.Column("workout_goal", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "user", sa.Column("workout_time_per_day", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "user", sa.Column("workout_time_period", sa.String(length=50), nullable=True)
    )
    op.alter_column(
        "user",
        "age",
        type=sa.INTEGER(),
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        nullable=False,
    )
    op.alter_column(
        "user",
        "weight",
        type=sa.INTEGER(),
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        nullable=False,
    )
    op.alter_column(
        "user",
        "workout_per_week",
        type=sa.INTEGER(),
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        nullable=False,
    )
    op.drop_column("user", "latitude")
    op.drop_column("user", "longitude")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "longitude",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "latitude",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "user", "workout_per_week", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("user", "weight", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("user", "age", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("user", "workout_time_period")
    op.drop_column("user", "workout_time_per_day")
    op.drop_column("user", "workout_goal")
    op.drop_column("user", "workout_level")
    op.drop_column("user", "gender")
    op.drop_column("user", "height")
    # ### end Alembic commands ###
