"""Add cover image url field

Revision ID: 9399a779e11c
Revises: 73dd619f94b4
Create Date: 2022-09-14 15:09:03.979985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9399a779e11c'
down_revision = '73dd619f94b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio', sa.Column('cover_image_url', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio', 'cover_image_url')
    # ### end Alembic commands ###
