"""Add prototyping model

Revision ID: b10d8bb4a8cb
Revises: 9399a779e11c
Create Date: 2022-11-01 16:51:17.219774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b10d8bb4a8cb'
down_revision = '9399a779e11c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prototyping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prototyping_id'), 'prototyping', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prototyping_id'), table_name='prototyping')
    op.drop_table('prototyping')
    # ### end Alembic commands ###
