"""add promise location to workout promise

Revision ID: b14cf3d76b6e
Revises: 2bf2915736c5
Create Date: 2023-08-21 16:14:33.359975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.models.guid

# revision identifiers, used by Alembic.
revision = "b14cf3d76b6e"
down_revision = "2bf2915736c5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promise_location",
        sa.Column("id", app.models.guid.GUID(), nullable=False),
        sa.Column("place_name", sa.String(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promise_location")),
    )
    op.create_index(op.f("ix_promise_location_id"), "promise_location", ["id"], unique=False)
    op.add_column(
        "workout_promise",
        sa.Column("promise_location_id", app.models.guid.GUID(), nullable=True),
    )
    op.drop_constraint("fk_workout_promise_gym_info_id_gym_info", "workout_promise", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_workout_promise_promise_location_id_promise_location"),
        "workout_promise",
        "promise_location",
        ["promise_location_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("workout_promise", "gym_info_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workout_promise",
        sa.Column("gym_info_id", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        op.f("fk_workout_promise_promise_location_id_promise_location"),
        "workout_promise",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_workout_promise_gym_info_id_gym_info",
        "workout_promise",
        "gym_info",
        ["gym_info_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("workout_promise", "promise_location_id")
    op.drop_index(op.f("ix_promise_location_id"), table_name="promise_location")
    op.drop_table("promise_location")
    # ### end Alembic commands ###
