"""fix ondelete notifiaton

Revision ID: cdf2108ed38d
Revises: 35fc620e3894
Create Date: 2023-03-30 20:06:55.575912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf2108ed38d'
down_revision = '35fc620e3894'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_notification_workout_sender_id_workout_participant', 'notification_workout', type_='foreignkey')
    op.drop_constraint('fk_notification_workout_recipient_id_workout_participant', 'notification_workout', type_='foreignkey')
    op.create_foreign_key(op.f('fk_notification_workout_sender_id_workout_participant'), 'notification_workout', 'workout_participant', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_notification_workout_recipient_id_workout_participant'), 'notification_workout', 'workout_participant', ['recipient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_notification_workout_recipient_id_workout_participant'), 'notification_workout', type_='foreignkey')
    op.drop_constraint(op.f('fk_notification_workout_sender_id_workout_participant'), 'notification_workout', type_='foreignkey')
    op.create_foreign_key('fk_notification_workout_recipient_id_workout_participant', 'notification_workout', 'workout_participant', ['recipient_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_notification_workout_sender_id_workout_participant', 'notification_workout', 'workout_participant', ['sender_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
